name: ci

on:
  push:
  pull_request:

jobs:
  core:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: cmake -B build
    - name: build
      run: cmake --build build --parallel
    - name: test
      run: ctest --test-dir build/test -V
